/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LeaderboardEntry = IDL.Record({
  'combinedTotal' : IDL.Nat,
  'round1Total' : IDL.Nat,
  'team' : Team,
  'round2Total' : IDL.Nat,
});
export const Round1Score = IDL.Record({
  'problemUnderstanding' : IDL.Nat,
  'systemDesign' : IDL.Nat,
  'innovation' : IDL.Nat,
  'prototypeProgress' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'teamExplanation' : IDL.Nat,
});
export const Round2Score = IDL.Record({
  'realWorldImpact' : IDL.Nat,
  'technicalComplexity' : IDL.Nat,
  'uiUx' : IDL.Nat,
  'finalPrototype' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'functionality' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTeam' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTeams' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Vec(IDL.Nat)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTeam' : IDL.Func([IDL.Nat], [], []),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getTeamScores' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Round1Score), IDL.Opt(Round2Score)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRound1Score' : IDL.Func([IDL.Nat, Round1Score], [], []),
  'submitRound2Score' : IDL.Func([IDL.Nat, Round2Score], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LeaderboardEntry = IDL.Record({
    'combinedTotal' : IDL.Nat,
    'round1Total' : IDL.Nat,
    'team' : Team,
    'round2Total' : IDL.Nat,
  });
  const Round1Score = IDL.Record({
    'problemUnderstanding' : IDL.Nat,
    'systemDesign' : IDL.Nat,
    'innovation' : IDL.Nat,
    'prototypeProgress' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'teamExplanation' : IDL.Nat,
  });
  const Round2Score = IDL.Record({
    'realWorldImpact' : IDL.Nat,
    'technicalComplexity' : IDL.Nat,
    'uiUx' : IDL.Nat,
    'finalPrototype' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'functionality' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTeam' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addTeams' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Vec(IDL.Nat)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTeam' : IDL.Func([IDL.Nat], [], []),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getTeamScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Round1Score), IDL.Opt(Round2Score)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRound1Score' : IDL.Func([IDL.Nat, Round1Score], [], []),
    'submitRound2Score' : IDL.Func([IDL.Nat, Round2Score], [], []),
  });
};

export const init = ({ IDL }) => { return []; };