/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'combinedTotal' : bigint,
  'round1Total' : bigint,
  'team' : Team,
  'round2Total' : bigint,
}
export interface Round1Score {
  'problemUnderstanding' : bigint,
  'systemDesign' : bigint,
  'innovation' : bigint,
  'prototypeProgress' : bigint,
  'totalScore' : bigint,
  'teamExplanation' : bigint,
}
export interface Round2Score {
  'realWorldImpact' : bigint,
  'technicalComplexity' : bigint,
  'uiUx' : bigint,
  'finalPrototype' : bigint,
  'totalScore' : bigint,
  'functionality' : bigint,
}
export interface Team { 'id' : bigint, 'name' : string, 'description' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTeam' : ActorMethod<[string, string], bigint>,
  'addTeams' : ActorMethod<[Array<string>], Array<bigint>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTeam' : ActorMethod<[bigint], undefined>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTeamScores' : ActorMethod<
    [bigint],
    [[] | [Round1Score], [] | [Round2Score]]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRound1Score' : ActorMethod<[bigint, Round1Score], undefined>,
  'submitRound2Score' : ActorMethod<[bigint, Round2Score], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];